In [1]:
import numpy as np

In [2]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
for i in list_:
    print(type((i)))
    
print("")  

for i in array_list :
    print(type((i)))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [6]:
array_list = np.array(object = list_, dtype = int)

In [7]:
array_list

array([1, 2, 3, 4, 5])

In [8]:
for i in list_:
    print(type((i)))
    
print("")  

for i in array_list :
    print(type((i)))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [9]:
import numpy as np


In [10]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [12]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
num_array.shape

(2, 3)

In [14]:
num_array.size

6

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])